export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Azerbaijan",
  "Argentina",
  "Australia",
  "Austria",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Armenia",
  "Barbados",
  "Belgium",
  "Belgium-Luxembourg",
  "Bermuda",
  "Bhutan",
  "Plurinational State of Bolivia",
  "Bosnia Herzegovina",
  "Botswana",
  "Brazil",
  "Belize",
  "British Indian Ocean Territories",
  "Solomon Islands",
  "British Virgin Islands",
  "Brunei Darussalam",
  "Bulgaria",
  "Myanmar",
  "Burundi",
  "Belarus",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cabo Verde",
  "Cayman Islands",
  "Central African Republic",
  "Sri Lanka",
  "Chad",
  "Chile",
  "China",
  "Christmas Islands",
  "Cocos Islands",
  "Colombia",
  "Comoros",
  "Mayotte",
  "Congo",
  "Democratic Republic of the Congo",
  "Cook Islands",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechoslovakia",
  "Czechia",
  "Benin",
  "Denmark",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "El Salvador",
  "Equatorial Guinea",
  "Former Ethiopia",
  "Ethiopia",
  "Estonia",
  "Falkland Islands (Malvinas)",
  "Fiji",
  "Finland",
  "France, Monaco",
  "French Polynesia",
  "French South Antarctic Territories",
  "Djibouti",
  "Gabon",
  "Georgia",
  "Gambia",
  "State of Palestine",
  "Germany",
  "Former Democratic Republic of Germany",
  "Former Federal Republic of Germany",
  "Ghana",
  "Gibraltar",
  "Kiribati",
  "Greece",
  "Greenland",
  "Grenada",
  "Guam",
  "Guatemala",
  "Guinea",
  "Guyana",
  "Haiti",
  "Honduras",
  "China, Hong Kong Special Administrative Region",
  "Hungary",
  "Iceland",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "C魌e d'Ivoire",
  "Jamaica",
  "Japan",
  "Kazakhstan",
  "Jordan",
  "Kenya",
  "Democratic People's Republic of Korea",
  "Republic of Korea",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Dem. Rep.",
  "Lebanon",
  "Lesotho",
  "Latvia",
  "Liberia",
  "Libya",
  "Lithuania",
  "Luxembourg",
  "China, Macao Special Administrative Region",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Other Asia, not elsewhere specified",
  "Mongolia",
  "Republic of Moldova",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Oman",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "Cura鏰o",
  "Aruba",
  "Saint Maarten (Dutch part)",
  "Bonaire, Saint Eustatius and Saba",
  "New Caledonia",
  "Vanuatu",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Islands",
  "Norway, Svalbard and Jan Mayen",
  "Northern Mariana Islands",
  "Federated State of Micronesia",
  "Marshall Islands",
  "Palau",
  "Pakistan",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Guinea-Bissau",
  "Timor-Leste",
  "Qatar",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Barth閘emy",
  "Saint Helena",
  "Saint Kitts and Nevis",
  "Anguilla",
  "Saint Lucia",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Europe EFTA, not elsewhere specified",
  "India",
  "Singapore",
  "Slovakia",
  "Viet Nam",
  "Slovenia",
  "Somalia",
  "South Africa",
  "Southern African Customs Union",
  "Zimbabwe",
  "Spain",
  "South Sudan",
  "Sudan",
  "Former Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland, Liechtenstein",
  "Syria",
  "Tajikistan",
  "Thailand",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "United Arab Emirates",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "The Former Yugoslav Republic of Macedonia",
  "Former USSR",
  "Egypt",
  "United Kingdom",
  "United Republic of Tanzania",
  "USA, Puerto Rico and US Virgin Islands",
  "US Miscellaneous Pacific Islands",
  "Burkina Faso",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Wallis and Futuna Islands",
  "Samoa",
  "Yemen",
  "Serbia and Montenegro",
  "Zambia",
];
